# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["**"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  checkout-matrix:
    strategy:
      matrix:
        branch: [ "gha-pages", "0.6" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          path: ${{ matrix.branch }}
          clean: false
      # Delete the .git folder
      # This turns the files into a plain folder instead of a git repository
      - run: rm -rf ${{ matrix.branch }}/.git

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Output target url
        run: echo ${{ steps.deployment.outputs.page_url }}${{ github.ref_name }}
